### ISSUE TITLE
SWIM support

### ISSUE THREAD

**Issue by dzid26** [klonyyy/MCUViewer#70]
STM Studio had SWIM protocol for STM8
<img width="193" alt="Screenshot 2024-06-05 002914" src="https://github.com/klonyyy/STMViewer/assets/841061/980e19da-caf2-4621-950c-209a243e5879">

It would be great to add this.

Libraries that could be useful:
https://github.com/afaerber/stlink/blob/master/libstlink/stlink.h 
https://github.com/openocd-org/openocd/blob/master/src/jtag/drivers/stlink_usb.c

**Comment by klonyyy** [comment]
I'm closing this issue due to the fact that maintaining another piece of software to support rarely used SWIM through STLink is just not worth the effort at this point. Now I'd rather support SWIM only on JLink probes as this requires much less effort to maintain. Please reopen/react to this message if there is a real need for SWIM protocol being supported.
